
OPTS = -c -O2 -Wall -Wno-non-virtual-dtor -DMAC

CC = g++

GL_INC = -I../../glew/include
GL_LIBS = -framework OpenGL -framework GLUT -lobjc -lGLEW -L../../glew/lib
LLDLIBS =  $(GL_LIBS) -L/usr/X11R6/lib
OBJECTS = main.o math.o scene.o vbo.o
TARGET = ../bin/grass_benchmark.mac

all: $(TARGET)

.cpp.o:
		$(CC) $(OPTS) $(GL_INC) $<

.c.o:
		$(CC) $(OPTS) $(GL_INC) $<

$(TARGET):	$(OBJECTS)
		$(CC) -o $(TARGET) $(OBJECTS) $(LLDLIBS)

clean:  
	-rm -f *.o

distclean: clean
	rm -f *~ $(TARGET)
